
import { create } from 'zustand';
import { MenuItem, MenuCategory, MenuSubcategory } from '@/types/menu';

interface MenuState {
  categories: MenuCategory[];
  menuItems: MenuItem[];
  selectedCategory: string | null;
  selectedSubcategory: string | null;
  loading: boolean;
  error: string | null;
  setSelectedCategory: (category: string | null) => void;
  setSelectedSubcategory: (subcategory: string | null) => void;
  setMenuItems: (items: MenuItem[]) => void;
  setCategories: (categories: MenuCategory[]) => void;
  setLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
}

// Sample subcategories
const saladSubcategories: MenuSubcategory[] = [
  { id: 'warm-options', name: 'Warm Options', categoryId: 'salads' },
  { id: 'pick-your-protein', name: 'Pick Your Protein', categoryId: 'salads' },
  { id: 'plant-based', name: 'Plant Based', categoryId: 'salads' },
  { id: 'meat', name: 'Meat', categoryId: 'salads' },
  { id: 'fish', name: 'Fish', categoryId: 'salads' },
];

const baoSubcategories: MenuSubcategory[] = [
  { id: 'regular', name: 'Regular', categoryId: 'bao' },
  { id: 'plant-based', name: 'Plant based', categoryId: 'bao' },
];

const sushiSubcategories: MenuSubcategory[] = [
  { id: 'maki', name: 'Maki', categoryId: 'sushi' },
  { id: 'nigiri', name: 'Nigiri', categoryId: 'sushi' },
  { id: 'mix', name: 'Mix', categoryId: 'sushi' },
];

// Sample data for development
const sampleCategories: MenuCategory[] = [
  { 
    id: 'salads', 
    name: 'Salads', 
    description: 'Fresh & Healthy', 
    order: 1,
    subcategories: saladSubcategories
  },
  { 
    id: 'bao', 
    name: 'Bao', 
    description: 'Steamed Buns', 
    order: 2,
    subcategories: baoSubcategories
  },
  { 
    id: 'sushi', 
    name: 'Sushi', 
    description: 'Fresh Rolls', 
    order: 3,
    subcategories: sushiSubcategories
  },
  { 
    id: 'sides', 
    name: 'Sides', 
    description: 'Perfect Accompaniments', 
    order: 4 
  },
  { 
    id: 'drinks', 
    name: 'Drinks', 
    description: 'Refreshing Beverages', 
    order: 5 
  },
];

const sampleMenuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Holy Cow',
    description: 'Yakiniku Entrecôte, Salad mix. Kimchi cabbage, Cucumber, Radishes, Chilli mayonnaise, Gochujang glaze, Green onions, Rice puffs',
    price: 150,
    categories: ['salads'],
    subcategories: ['warm-options', 'meat'], // ✅ now supports multiple subcategories
    tags: ['NEW'],
    available: true,
    image: '/images/holy-cow.PNG',
  },
  {
    id: '2',
    name: 'Crispy Chicken',
    description: 'Panko-Fried Chicken, Chili Mayonnaise, Teriyaki Sauce, Salad Mix (White Cabbage, Red Cabbage, Carrot), Kale, Radishes, Edamame Beans. Green Onion. Sesame Seeds',
    price: 135,
    categories: ['salads'],
    subcategories: ['warm-options', 'meat'],
    tags: ['Popular'],
    available: true,
    image: '/images/crispy-chicken.jpeg',
  },
  {
    id: '3',
    name: 'Miso Salmon',
    description: 'Grilled miso salmon, Chili mayonnaise, Salad mix (white cabbage, red cabbage, carrot), Kale, Radishes, Edamame beans, Green onions, Coriander, Umami Crunch (Cashew. Almonds, Chili flakes, Pumpkin seeds. Sesame seeds)',
    price: 145,
    categories: ['salads'],
    subcategories: ['warm-options', 'fish'],
    tags: [],
    available: true,
    image: '/images/miso-salmon.JPG',
  },
  {
    id: '4',
    name: 'The Shrimp',
    description: 'Hand-peeled shrimp, Chili mayonnaise, Salad mix (white cabbage, red cabbage, carrot), Kale, Edamame beans, Cucumber, Seaweed salad, Mango salsa, Wasabi peas **🌶️',
    price: 150,
    categories: ['salads'],
    subcategories: ['fish'],
    tags: [],
    available: true,
    image: '/images/the-shrimp.JPG',
  },
  {
    id: '5',
    name: 'Caesar Me',
    description: 'Miso-Ceasar dressing, Romaine lettuce, Kale, Red onion, Cherry tomato, Panko, Bacon, Black pepper & Grana Padano',
    price: 135,
    categories: ['salads'],
    subcategories: ['warm-options', 'meat', 'fish','pick-your-protein'],
    tags: [''],
    available: true,
    image: '/images/caesar-me.JPG',
  },
  {
    id: '6',
    name: 'The OG',
    description: 'Sesame dressing (Vegan), Salad mix (white cabbage, red cabbage, carrot), Kale, Radishes, Edamame beans, Red onion, Seaweed salad, Sesame seeds, Chili Flakes, & Rice puffs',
    price: 135,
    categories: ['salads'],
    subcategories: ['warm-options', 'meat', 'plant-based', 'fish','pick-your-protein'],
    tags: ['Vegan Option',],
    available: true,
    image: '/images/the-O.G.JPG',
  },
  {
    id: '8',
    name: 'Tofu Girl',
    description: 'Corn-Fried Tofu, Peanut Sauce, Salad Mix (White Cabbage, Red Cabbage, Carrot), Glass Noodles, Avocado, Mango Salsa, Lime, Coriander, Peanut Sprinkles, Sesame Seeds',
    price: 140,
    categories: ['salads'],
    subcategories: ['warm-options','plant-based'],
    tags: ['VGN'],
    available: true,
    image: '/images/tofu-girl.JPG',
  },
  {
    id: '9',
    name: 'Chick\'n Crispy',
    description: 'Panko-Friterad Kyckling, Kimchi kål, Picklad Morot, Chillimajonnäs, Sesamfrön, Salladslock, Chili',
    price: 120,
    categories: ['bao'],
    subcategories: ['regular'],
    tags: [],
    available: true,
    image: '/images/chick-n-crunch.jpeg',
  },
  {
    id: '10',
    name: 'Korean Chick\'n',
    description: 'Panko-Friterad Kyckling med gochujang glaze, Kimchi kål, Picklad Morot, Chillimajonnäs, Grana Padano, Salladslock, Chili',
    price: 120,
    categories: ['bao'],
    subcategories: ['regular'],
    tags: ['SPICY'],
    available: true,
    image: '/images/korean-chick-n.jpg',
  },
  {
    id: '12',
    name: 'Golden Tofu',
    description: 'Corn-Friterad Tofu, Kimchi kål, Picklad Morot, Chillimajonnäs, Sesamfrön, Koriander, Chili',
    price: 120,
    categories: ['bao'],
    subcategories: ['plant-based'],
    tags: ['VEG'],
    available: true,
    image: '/images/golden-tofu.jpeg',
  },
  {
    id: '13',
    name: 'Nutty Tofu',
    description: 'Corn-Friterad Tofu, Kimchi kål, Picklad Morot, Gurka, Jordnötssmör, Jordnötsspröjsel, Koriander, Chili',
    price: 120,
    categories: ['bao'],
    subcategories: ['plant-based'],
    tags: ['VGN'],
    available: true,
    image: '/images/nutty-tofu.jpeg',
  },
  {
    id: '14',
    name: 'Salmon Avo',
    description: 'Lax, Avokado, Gurka, Aioli. Toppad med: Chilimajonnäs, Sesamfrön, Krispig lök',
    price: 99,
    categories: ['sushi'],
    subcategories: ['maki','fish'],
    tags: ['Popular'],
    available: true,
    image: '/images/salmon-avo.JPG',
  },
  {
    id: '15',
    name: 'Luigi',
    description: 'Tempura Räkor, Gurka, Aioli. Toppad med: Avokado, Chilimajonnäs, Umami Crunch (Cashew, Mandlar, Chiliflakes, Pumpafrön, Sesam)',
    price: 119,
    categories: ['sushi'],
    subcategories: ['maki','fish'],
    tags: [],
    available: true,
    image: '/images/luigi.JPG',
  },
  {
    id: '16',
    name: 'See Me Rollin',
    description: 'Tempura Räkor, Gurka, Aioli. Toppad med: Tryffelmajo, Grana Padano, Rispuffar',
    price: 109,
    categories: ['sushi'],
    subcategories: ['maki','fish'],
    tags: [],
    available: true,
    image: '/images/see-me-rollin.JPG',
  },
  {
    id: '17',
    name: 'Rolls Royce',
    description: 'Tamago (ägg), Avokado, Gurka, Aioli. Toppad med: Tryffelmajo, Wasabi ärtor',
    price: 99,
    categories: ['sushi'],
    subcategories: ['maki','plant-based'],
    tags: ['VGN'],
    available: true,
    image: '/images/rolls-royce.JPG',
  },
  {
    id: '18',
    name: 'What The Fish',
    description: 'Tempura Räkor, Gurka. Toppad med: Halstrad miso lax, chillimajonnäs, Salladslök',
    price: 119,
    categories: ['sushi'],
    subcategories: ['maki','fish'],
    tags: [],
    available: true,
    image: '/images/wtf.JPG',
  },
  {
    id: '19',
    name: 'Kim Jong',
    description: 'Yakiniku Entrecôte, gurka, kimchi kål,chillimajonnäs. Topped with green onions and teriyaki.',
    price: 109,
    categories: ['sushi'],
    subcategories: ['maki','fish'],
    tags: [],
    available: true,
    image: '/images/kim-jong.JPG',
  },
  {
  id: '20',
  name: 'Avo Nigiri',
  description: 'Toppad med: Teriyakisås, Wasabi ärtor',
  price: 85,
  priceLabel: 'from 85',   // 👈 This will show on UI
  categories: ['sushi'],
  subcategories: ['nigiri','plant-based'],
  tags: ['VGN'],
  available: true,
  image: '/images/avo-nigiri.jpg',
},
  {
    id: '21',
    name: 'Lax Nigiri',
    description: 'Toppad med: Aioli, Salladslök',
    price: 90,
    priceLabel: 'from 90',
    categories: ['sushi'],
    subcategories: ['nigiri','fish'],
    tags: [],
    available: true,
    image: '/images/lax-nigiri.jpeg',
  },
  {
    id: '22',
    name: 'Miso Lax Nigiri',
    description: 'Halstrad lax, Toppad med: Chilimajonnäs, Salladslök',
    price: 90,
    priceLabel: 'from 90',
    categories: ['sushi'],
    subcategories: ['nigiri','fish'],
    tags: [],
    available: true,
    image: '/images/miso-lax-nigiri.jpg',
  },
  {
    id: '23',
    name: 'Truffled Lax Nigiri',
    description: 'Halstrad lax, Toppad med: Tryffelmajonnäs, Grana Padano, Rispuffar',
    price: 95,
    priceLabel: 'from 95',
    categories: ['sushi'],
    subcategories: ['nigiri','fish'],
    tags: [],
    available: true,
    image: '/images/truffled-lax-nigiri.jpg',
  },
  {
    id: '24',
    name: 'Mix (12 bitar)',
    description: 'Rullar: 2 Salmon Avo, 2 Sesam Tempura Räkor, 2 Tryffel Tempura Räkor. Nigiri: 2 Lax, 1 Halstrad lax, 1 Ebi Räkor, 2 Avo',
    price: 145,
    categories: ['sushi'],
    subcategories: ['mix','fish'],
    tags: [],
    available: true,
    image: '/images/12-bites.jpeg',
  },
  {
    id: '25',
    name: 'Mix (16 bitar)',
    description: 'Rullar: 2 Salmon Avo, 3 Sesam Tempura Räkor, 3 Tryffel Tempura Räkor. Nigiri: 3 Lax, 2 Halstrad lax, 1 Ebi Räkor, 2 Avo',
    price: 185,
    categories: ['sushi'],
    subcategories: ['mix','fish'],
    tags: [],
    available: true,
    image: '/images/16-bites.jpg',
  },
  {
    id: '26',
    name: 'Mix (30 bitar)',
    description: 'Rullar: 4 Salmon Avo, 5 Sesam Tempura Räkor, 5 Tryffel Tempura Räkor. Nigiri: 6 Lax, 3 Halstrad lax, 3 Ebi Räkor, 4 Avo',
    price: 340,
    categories: ['sushi'],
    subcategories: ['mix','fish'],
    tags: [],
    available: true,
    image: '/images/30-bites.png',
  },
  {
    id: '27',
    name: 'Bang Bang Shrimp',
    description: 'Tempura Shrimp, Chillimayo, Green Onion',
    price:60,
    categories: ['sides'],
    subcategories: [''],
    tags: ['Popular'],
    available: true,
    image: '/images/bang-bang-shrimp.jpg',
  },
  {
    id: '28',
    name: 'Chicken Popcorn',
    description: 'Chicken pops, Chilli mayonnaise, Green onions',
    price: 60,
    categories: ['sides'],
    subcategories: [''],
    tags: ['Popular'],
    available: true,
    image: '/images/chicken-pop.jpg',
  },
  {
    id: '29',
    name: 'Wakame',
    description: 'Seaweed salad',
    price: 30,
    categories: ['sides'],
    subcategories: [''],
    tags: [],
    available: true,
    image: '/images/wakame.jpg',
  },
  {
    id: '30',
    name: 'Mango salsa',
    description: 'Mango, Tomato, Red Onion, Red Chilli, Lime',
    price: 30,
    categories: ['sides'],
    subcategories: [''],
    tags: [],
    available: true,
    image: '/images/mango-salsa.jpg',
  },
  {
    id: '31',
    name: 'Avocado Smash',
    description: 'Avocado, Sesame seeds',
    price: 20,
    categories: ['sides'],
    subcategories: [''],
    tags: [],
    available: true,
    image: '/images/avocado-smash.jpg',
  },
  {
    id: '32',
    name: 'Miso Soup',
    description: 'Miso paste (Vegan), Seaweed and Green onions',
    price: 20,
    categories: ['sides'],
    subcategories: [''],
    tags: [],
    available: true,
    image: '/images/miso-soup.jpg',
  },
  {
    id: '33',
    name: 'Kimino UME',
    description: 'Sparkling Water, Wakayama Pressed Ume, Organic Sugar cane',
    price: 45,
    categories: ['drinks'],
    subcategories: [''],
    tags: [],
    available: true,
    image: '/images/ume.PNG',
  },
];

export const useMenuStore = create<MenuState>((set) => ({
  categories: sampleCategories,
  menuItems: sampleMenuItems,
  selectedCategory: null,
  selectedSubcategory: null,
  loading: false,
  error: null,
  setSelectedCategory: (category) => set({ selectedCategory: category, selectedSubcategory: null }),
  setSelectedSubcategory: (subcategory) => set({ selectedSubcategory: subcategory }),
  setMenuItems: (items) => set({ menuItems: items }),
  setCategories: (categories) => set({ categories }),
  setLoading: (loading) => set({ loading }),
  setError: (error) => set({ error }),
}));
