
import { create } from 'zustand';
import { MenuItem, MenuCategory, MenuSubcategory } from '@/types/menu';

interface MenuState {
  categories: MenuCategory[];
  menuItems: MenuItem[];
  selectedCategory: string | null;
  selectedSubcategory: string | null;
  loading: boolean;
  error: string | null;
  setSelectedCategory: (category: string | null) => void;
  setSelectedSubcategory: (subcategory: string | null) => void;
  setMenuItems: (items: MenuItem[]) => void;
  setCategories: (categories: MenuCategory[]) => void;
  setLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
}

// Sample subcategories
const saladSubcategories: MenuSubcategory[] = [
  { id: 'warm-salads', name: 'Warm Salads', categoryId: 'salads' },
  { id: 'cold-salads', name: 'Cold Salads', categoryId: 'salads' },
  { id: 'veg-salads', name: 'Veg (Vegetarian)', categoryId: 'salads' },
  { id: 'vgn-salads', name: 'Vgn (Vegan)', categoryId: 'salads' },
];

const baoSubcategories: MenuSubcategory[] = [
  { id: 'regular-bao', name: 'Regular', categoryId: 'bao' },
  { id: 'veg-bao', name: 'Veg (Vegetarian)', categoryId: 'bao' },
  { id: 'vgn-bao', name: 'Vgn (Vegan)', categoryId: 'bao' },
];

const sushiSubcategories: MenuSubcategory[] = [
  { id: 'maki', name: 'Maki', categoryId: 'sushi' },
  { id: 'nigiri', name: 'Nigiri', categoryId: 'sushi' },
  { id: 'mix', name: 'Mix', categoryId: 'sushi' },
];

// Sample data for development
const sampleCategories: MenuCategory[] = [
  { 
    id: 'salads', 
    name: 'Salads', 
    description: 'Fresh & Healthy', 
    order: 1,
    subcategories: saladSubcategories
  },
  { 
    id: 'bao', 
    name: 'Bao', 
    description: 'Steamed Buns', 
    order: 2,
    subcategories: baoSubcategories
  },
  { 
    id: 'sushi', 
    name: 'Sushi', 
    description: 'Fresh Rolls', 
    order: 3,
    subcategories: sushiSubcategories
  },
  { 
    id: 'sides', 
    name: 'Sides', 
    description: 'Perfect Accompaniments', 
    order: 4 
  },
  { 
    id: 'drinks', 
    name: 'Drinks', 
    description: 'Refreshing Beverages', 
    order: 5 
  },
];

const sampleMenuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Holy Cow',
    description: 'Yakiniku Entrecôte, Salad mix. Kimchi cabbage, Cucumber, Radishes, Chilli mayonnaise, Gochujang glaze, Green onions, Rice puffs **🌶️🌶️',
    price: 140,
    category: 'salads',
    tags: ['NEW'],
    available: true,
    image: '/images/holy-cow.jpg',
  },
  {
    id: '2',
    name: 'Crispy Chicken',
    description: 'Panko-Fried Chicken, Chili Mayonnaise, Teriyaki Sauce, Salad Mix (White Cabbage, Red Cabbage, Carrot), Kale, Radishes, Edamame Beans. Green Onion. Sesame Seeds',
    price: 125,
    category: 'salads',
    tags: ['Popular'],
    available: true,
    image: '/images/crispy-chicken.jpeg',
  },
  {
    id: '3',
    name: 'Miso Salmon',
    description: 'Grilled miso salmon, Chili mayonnaise, Salad mix (white cabbage, red cabbage, carrot), Kale, Radishes, Edamame beans, Green onions, Coriander, Umami Crunch (Cashew. Almonds, Chili flakes, Pumpkin seeds. Sesame seeds)',
    price: 135,
    category: 'salads',
    tags: [],
    available: true,
    image: '/images/miso-salmon.JPG',
  },
  {
    id: '4',
    name: 'The Shrimp',
    description: 'Hand-peeled shrimp, Chili mayonnaise, Salad mix (white cabbage, red cabbage, carrot), Kale, Edamame beans, Cucumber, Seaweed salad, Mango salsa, Wasabi peas **🌶️',
    price: 140,
    category: 'salads',
    tags: [],
    available: true,
    image: '/images/the-shrimp.JPG',
  },
  {
    id: '5',
    name: 'Caesar Me',
    description: 'Miso-Ceasar dressing, Romaine lettuce, Kale, Red onion, Cherry tomato, Panko, Bacon, Black pepper & Grana Padano',
    price: 125,
    category: 'salads',
    tags: [],
    available: true,
    image: '/images/caesar-me.JPG',
  },
  {
    id: '6',
    name: 'The OG',
    description: 'Sesame dressing (Vegan), Salad mix (white cabbage, red cabbage, carrot), Kale, Radishes, Edamame beans, Red onion, Seaweed salad, Sesame seeds, Chili Flakes, & Rice puffs',
    price: 125,
    category: 'salads',
    tags: ['Vegan Option'],
    available: true,
    image: '/images/the-O.G.JPG',
  },
  {
    id: '7',
    name: 'Good morning Vietnam',
    description: 'Ginger-lime dressing, Salad mix (white cabbage, red cabbage, carrot), Glass noodles, Cucumber, Red onion, Mint, Cherry tomato, Crispy onion, Peanut sprinkles',
    price: 125,
    category: 'salads',
    tags: [],
    available: true,
    image: '/images/G-M-V.JPG',
  },
  {
    id: '8',
    name: 'Tofu Girl',
    description: 'Corn-Fried Tofu, Peanut Sauce, Salad Mix (White Cabbage, Red Cabbage, Carrot), Glass Noodles, Avocado, Mango Salsa, Lime, Coriander, Peanut Sprinkles, Sesame Seeds',
    price: 130,
    category: 'salads',
    tags: ['VGN'],
    available: true,
    image: '/images/tofu-girl.JPG',
  },
  {
    id: '9',
    name: 'Chick\'n Crispy',
    description: 'Panko-Friterad Kyckling, Kimchi kål, Picklad Morot, Chillimajonnäs, Sesamfrön, Salladslock, Chili',
    price: 120,
    category: 'bao',
    tags: [],
    available: true,
    image: '/images/chick-n-crunch.jpeg',
  },
  {
    id: '10',
    name: 'Korean Chick\'n',
    description: 'Panko-Friterad Kyckling med gochujang glaze, Kimchi kål, Picklad Morot, Chillimajonnäs, Grana Padano, Salladslock, Chili',
    price: 120,
    category: 'bao',
    tags: ['SPICY'],
    available: true,
    image: '/images/korean-chick-n.jpg',
  },
  {
    id: '11',
    name: 'Magic Mushroom',
    description: 'Panko-Friterad champinjon, Kimchi kål, Picklad Morot, Chillimajonnäs, Salladslock, Rispuffar, Chili',
    price: 120,
    category: 'bao',
    tags: ['VEG'],
    available: true,
    image: '/images/magic-mashroom.jpg',
  },
  {
    id: '12',
    name: 'Golden Tofu',
    description: 'Corn-Friterad Tofu, Kimchi kål, Picklad Morot, Chillimajonnäs, Sesamfrön, Koriander, Chili',
    price: 120,
    category: 'bao',
    tags: ['VEG'],
    available: true,
    image: '/images/golden-tofu.jpeg',
  },
  {
    id: '13',
    name: 'Nutty Tofu',
    description: 'Corn-Friterad Tofu, Kimchi kål, Picklad Morot, Gurka, Jordnötssmör, Jordnötsspröjsel, Koriander, Chili',
    price: 120,
    category: 'bao',
    tags: ['VGN'],
    available: true,
    image: '/images/nutty-tofu.jpeg',
  },
  {
    id: '14',
    name: 'Salmon Avo',
    description: 'Lax, Avokado, Gurka, Aioli. Toppad med: Chilimajonnäs, Sesamfrön, Krispig lök',
    price: 89,
    category: 'sushi',
    subcategory: 'maki',
    tags: [],
    available: true,
    image: '/images/salmon-avo.JPG',
  },
  {
    id: '15',
    name: 'Luigi',
    description: 'Tempura Räkor, Gurka, Aioli. Toppad med: Avokado, Chilimajonnäs, Umami Crunch (Cashew, Mandlar, Chiliflakes, Pumpafrön, Sesam)',
    price: 109,
    category: 'sushi',
    subcategory: 'maki',
    tags: [],
    available: true,
    image: '/images/luigi.JPG',
  },
  {
    id: '16',
    name: 'See Me Rollin',
    description: 'Tempura Räkor, Gurka, Aioli. Toppad med: Tryffelmajo, Grana Padano, Rispuffar',
    price: 99,
    category: 'sushi',
    subcategory: 'maki',
    tags: [],
    available: true,
    image: '/images/see-me-rollin.JPG',
  },
  {
    id: '17',
    name: 'Rolls Royce',
    description: 'Tamago (ägg), Avokado, Gurka, Aioli. Toppad med: Tryffelmajo, Wasabi ärtor',
    price: 89,
    category: 'sushi',
    subcategory: 'maki',
    tags: ['VGN'],
    available: true,
    image: '/images/rolls-royce.JPG',
  },
  {
    id: '18',
    name: 'What The Fish',
    description: 'Tamago (ägg), Gurka, Avokado. Toppad med: Halstrad miso lax, Aioli, Salladslök, Ingefära',
    price: 99,
    category: 'sushi',
    subcategory: 'maki',
    tags: [],
    available: true,
    image: '/images/wtf.JPG',
  },
  {
    id: '19',
    name: 'Avo Nigiri',
    description: 'Toppad med: Teriyakisås, Wasabi ärtor',
    price: 85,
    category: 'sushi',
    subcategory: 'nigiri',
    tags: ['VGN'],
    available: true,
    image: '/images/avo-nigiri.jpg',
  },
  {
    id: '20',
    name: 'Lax Nigiri',
    description: 'Toppad med: Aioli, Salladslök',
    price: 90,
    category: 'sushi',
    subcategory: 'nigiri',
    tags: [],
    available: true,
    image: '/images/lax-nigiri.jpeg',
  },
  {
    id: '21',
    name: 'Miso Lax Nigiri',
    description: 'Halstrad lax, Toppad med: Chilimajonnäs, Salladslök',
    price: 90,
    category: 'sushi',
    subcategory: 'nigiri',
    tags: [],
    available: true,
    image: '/images/miso-lax-nigiri.jpg',
  },
  {
    id: '22',
    name: 'Truffled Lax Nigiri',
    description: 'Halstrad lax, Toppad med: Tryffelmajonnäs, Grana Padano, Rispuffar',
    price: 95,
    category: 'sushi',
    subcategory: 'nigiri',
    tags: [],
    available: true,
    image: '/images/truffled-lax-nigiri.jpg',
  },
  {
    id: '23',
    name: 'Mix (12 bitar)',
    description: 'Rullar: 2 Salmon Avo, 2 Sesam Tempura Räkor, 2 Tryffel Tempura Räkor. Nigiri: 2 Lax, 1 Halstrad lax, 1 Ebi Räkor, 2 Avo',
    price: 139,
    category: 'sushi',
    subcategory: 'mix',
    tags: [],
    available: true,
    image: '/images/12-bites.jpeg',
  },
  {
    id: '24',
    name: 'Mix (16 bitar)',
    description: 'Rullar: 2 Salmon Avo, 3 Sesam Tempura Räkor, 3 Tryffel Tempura Räkor. Nigiri: 3 Lax, 2 Halstrad lax, 1 Ebi Räkor, 2 Avo',
    price: 185,
    category: 'sushi',
    subcategory: 'mix',
    tags: [],
    available: true,
    image: '/images/16-bites.jpg',
  },
  {
    id: '25',
    name: 'Mix (30 bitar)',
    description: 'Rullar: 4 Salmon Avo, 5 Sesam Tempura Räkor, 5 Tryffel Tempura Räkor. Nigiri: 6 Lax, 3 Halstrad lax, 3 Ebi Räkor, 4 Avo',
    price: 330,
    category: 'sushi',
    subcategory: 'mix',
    tags: [],
    available: true,
    image: '/images/30-bites.png',
  },
  {
    id: '26',
    name: 'Bang Bang Shrimp',
    description: 'Tempura Shrimp, Chillimayo, Green Onion',
    price: 55,
    category: 'sides',
    tags: [],
    available: true,
    image: '/images/bang-bang-shrimp.jpg',
  },
  {
    id: '27',
    name: 'Chicken Popcorn',
    description: 'Chicken pops, Chilli mayonnaise, Green onions',
    price: 55,
    category: 'sides',
    tags: [],
    available: true,
    image: '/images/chicken-pop.jpg',
  },
  {
    id: '28',
    name: 'Chilli Cheese Pickers',
    description: 'Jalapeño-Cheese nuggets with gochujang glaze, sesame seeds',
    price: 55,
    category: 'sides',
    tags: [],
    available: true,
    image: '/images/pickers.jpg',
  },
  {
    id: '29',
    name: 'Wakame',
    description: 'Seaweed salad',
    price: 25,
    category: 'sides',
    tags: [],
    available: true,
    image: '/images/wakame.jpg',
  },
  {
    id: '30',
    name: 'Mango salsa',
    description: 'Mango, Tomato, Red Onion, Red Chilli, Lime',
    price: 20,
    category: 'sides',
    tags: [],
    available: true,
    image: '/images/mango-salsa.jpg',
  },
  {
    id: '31',
    name: 'Avocado Smash',
    description: 'Avocado, Sesame seeds',
    price: 20,
    category: 'sides',
    tags: [],
    available: true,
    image: '/images/avocado-smash.jpg',
  },
  {
    id: '32',
    name: 'Miso Soup',
    description: 'Miso paste (Vegan), Seaweed and Green onions',
    price: 55,
    category: 'sides',
    tags: [],
    available: true,
    image: '/images/miso-soup.jpg',
  },
];

export const useMenuStore = create<MenuState>((set) => ({
  categories: sampleCategories,
  menuItems: sampleMenuItems,
  selectedCategory: null,
  selectedSubcategory: null,
  loading: false,
  error: null,
  setSelectedCategory: (category) => set({ selectedCategory: category, selectedSubcategory: null }),
  setSelectedSubcategory: (subcategory) => set({ selectedSubcategory: subcategory }),
  setMenuItems: (items) => set({ menuItems: items }),
  setCategories: (categories) => set({ categories }),
  setLoading: (loading) => set({ loading }),
  setError: (error) => set({ error }),
}));
